version: '3.1'
services:
  motorcalculoservice:
    image: motor-calculo:00.00.01
    ports:
    - "8080"
    networks:
        - vpcbr
networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.6.0.0/16